name: 
channels:
  - defaults
  - anaconda
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.5.2
  - numpy=1.21.5
  - pandas=1.4.4
  - pip=22.1.2
  - python=3.10.4
  - scikit-learn=1.1.1
  - scipy=1.7.3
  - seaborn=1.4.4
  - imbalanced-learn=0.11.1
  - xgboost==1.7.6
  - Pillow=10.0.0
  - pip:
    - "Kivy[base,media]"